# Generated by Django 4.2.6 on 2023-10-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_remove_instruction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
