# Generated by Django 4.2.6 on 2023-11-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0003_instruction_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Электрические схемы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображения')),
            ],
        ),
    ]
