# Generated by Django 4.2.6 on 2023-11-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0006_rename_shema_sсheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malfunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Неисправности')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображения')),
            ],
        ),
    ]
