# Generated by Django 4.2.6 on 2023-11-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0007_malfunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunctions',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
