# Generated by Django 4.2.6 on 2024-02-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
    ]
